# A string used to distinguish different Supabase projects on the same host.
# Defaults to the working directory name when running `supabase init`.
[api]
project_id = "judy"

# Port to use for the API URL.
port = 54321

[db]
# Port to use for the local database URL.
port = 54322

[studio]
# Port to use for Supabase Studio.
port = 54323

[inbucket]
# Port to use for the email testing server web interface.
port = 54324

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for
# constructing URLs used in emails.
site_url = "http://localhost:3000"

# A list of *exact* URLs that auth providers are permitted to redirect to post
# authentication.
additional_redirect_urls = ["https://localhost:3000"]

# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum
# 604,800 (1 week).
jwt_expiry = 3600

# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true

# Allows refresh tokens to be reused after expiry, up to the specified interval
# in seconds.  Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10

# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true

# If enabled, a user will be required to confirm any email change on both the
# old, and new email addresses. If disabled, only the new email is required to
# confirm.
double_confirm_changes = true

# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

[functions]
# Enables Edge Functions support.
enabled = true
